### PR TITLE
7.2 additions

### PR DESCRIPTION
**Pull request by jimmsta**
[some_new_maps.txt](https://github.com/bloerwald/LegionFiles/files/721779/some_new_maps.txt)
[additional_textures.txt](https://github.com/bloerwald/LegionFiles/files/721780/additional_textures.txt)
[ABWinter_wmos.txt](https://github.com/bloerwald/LegionFiles/files/721782/ABWinter_wmos.txt)

### CODE REVIEW

**Comment by bloerwald** [comment]
Manually merged and normalized in 8520452e8b5727996d1f6164e3bdbbff7bde9dab.

**Comment by jimmsta** [comment]
[7.2.x-map-additions.txt](https://github.com/bloerwald/LegionFiles/files/721797/7.2.x-map-additions.txt)

The rest of the new maps

**Comment by hoxton22** [comment]
Sorry i didn't have forked a branch yet, but i want to be a little bit helpful with that

Here are some path i have found : http://pastebin.com/QmTKTuw9

**Comment by bloerwald** [comment]
Thanks Manshaï, I manually merged those.

**Comment by hoxton22** [comment]
You are welcome ! :)

**Comment by jimmsta** [comment]
More additions for the latest build: https://gist.github.com/jimmsta/ae8504a7e5d96bdc2fb255316b14d4b6

**Comment by hoxton22** [comment]
Here are some news additions : https://ghostbin.com/paste/ct5nc

**Comment by bloerwald** [comment]
Both merged. 

Can you do me a favour and either make a new issue per addition or a merge request just adding the additions as a file, so I can better keep track of you? I currently do so by keeping the comment notification mails in my inbox, which isn't exactly the best solution.

**Comment by hoxton22** [comment]
Ok, i will make a new issue for each new additions

**Pull request closed without merging**
