### PR TITLE
updates from bloerwald

### PR DESCRIPTION
**Pull request by WainPetopia**

### CODE REVIEW

**Comment by bloerwald** [comment]
narf, sorry, I merged #70 before yours, which included some of yours and now yours is fucked. can you do me the favour and rebase your master onto mine?

**Comment by WainPetopia** [comment]
I still can't find reliable info on how to rebase my fork using the web interface. I simply delete it and start again :P

**Comment by WainPetopia** [comment]
BTW, there seems to be some switching back and forth between people who use \l and those who use \n\l at the end of lines. It really upsets SourceTree every time someone switches it. Is there a way you prefer?

**Comment by Marlamin** [comment]
We should probably have normalize script or git take care of that. Hasn't
been an issue here yet but I can understand some applications might have
issues with it.

**Comment by bloerwald** [comment]
It does? Fuck, I wouldn't have merged a single switch if I knew. I do look at every diff merged before merging but that does not seem to show that for whatever reason. 

I personally prefer \n.

**Comment by Marlamin** [comment]
I'm not sure which we should go for. Listfiles are used on many different operating systems. Wouldn't the most globally compatible option be CRLF? It's not optimal for those on OSX or Linux but it'd at least not cause breakage in some Windows editors.

**Comment by WainPetopia** [comment]
I tend to prefer \n as well. I wouldn't care too much but it's such a huge file and when the line endings change it marks the whole thing as one huge block change :/

**Comment by Marlamin** [comment]
\n it is!

**Comment by Marlamin** [comment]
Actually, it seems we already strip \r in normalize.sh. Are you sure you're running it each time before opening a PR?

**Pull request closed without merging**
